# Generated by Django 4.0.6 on 2022-09-26 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='제목')),
                ('content', models.TextField(max_length=50000, verbose_name='내용')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('views', models.PositiveSmallIntegerField(default=0, verbose_name='조회수')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
        ),
    ]
